---
- hosts: localhost
  become: true
  tasks:
  - name: "Installing tomcat"
    apt:
      name: tomcat8
      state: present

  - name: "starting tomcat service"
    service:
      name: tomcat8
      state: started

  - name: "Deploying jenkis tomcat"
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.107.1/jenkins.war
      dest: /var/lib/tomcat8/webapps/jenkins.war
      mode: 0755

    notify: "restart tomcat"
  handlers:
  - name: "restart tomcat"
    service:
      name: tomcat
      state: restarted
        