---
- hosts: localhost
  become: true
  tasks:
  - name: "Installing tomcat"
    apt:
      name: tomcat
      state: present
  - name: "starting tomcat service"
    service:
      name: tomcat    
      state: started
      enable: yes
  - name: "Deploying jenkis tomcat"
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.107.1/jenkins.war  
      dest: /usr/local/tomcat/webapps/jenkins.war
    notify: "restart tomcat"    

- handlers: 
  - name: "restart tomcat"
    service:
      name: tomcat
      state: restarted
        